import { Layout } from "@/components";
import { appName } from "@/utils";
import Head from "next/head";
import React from "react";

const Units = () => {
  return (
    <>
      <Head>
        <title>{`${appName} - ${"Units"}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout title="Units">Units</Layout>
    </>
  );
};

export default Units;
