import { Layout } from "@/components";
import { appName } from "@/utils";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const MosqueDetails = () => {
  const router = useRouter();
  const { id, title } = router.query;

  return (
    <>
      <Head>
        <title>{`${appName} - ${title}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout title={title as string}>
        <main className="flex flex-grow flex-col gap-8 p-4">
          <p>Mosque ID: {id}</p>
        </main>
      </Layout>
    </>
  );
};

export default MosqueDetails;
