import { Actions } from "@/auth";
import { EmptyState, Layout, LoadingIndicator } from "@/components";
import { t } from "@/locales";
import { OrganisationItem } from "@/organisations";
import { api, appName, Routes } from "@/utils";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";

const MosqueDetails = () => {
  const router = useRouter();
  const { id, title } = router.query;

  const { data, isFetching } = api.mosque.getOneMosque.useQuery({
    id: id as string,
  });

  return (
    <>
      <Head>
        <title>{`${appName} - ${title}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout title={title as string} requiredActions={[Actions.MOSQUE_READ]}>
        <main className="flex flex-grow flex-col gap-8 p-4">
          {isFetching ? (
            <LoadingIndicator />
          ) : data.organisations.length < 1 ? (
            <EmptyState text={t.mosque.noOrganisationsFound} />
          ) : (
            data.organisations.map((organisation) => (
              <Link
                key={organisation.id}
                href={`${Routes.ORGANISATIONS}/${organisation.id}?title=${organisation.name}`}
              >
                <OrganisationItem organisation={organisation} />
              </Link>
            ))
          )}
        </main>
      </Layout>
    </>
  );
};

export default MosqueDetails;
