import { Layout } from "@/components";
import { appName } from "@/utils";
import Head from "next/head";
import React from "react";

const Mosques = () => {
  return (
    <>
      <Head>
        <title>{`${appName} - ${"Mosques"}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout title="Mosques">Mosques</Layout>
    </>
  );
};

export default Mosques;
