import { Layout } from "@/components";
import { appName, unitNavItems } from "@/utils";
import Head from "next/head";
import React from "react";

const Categories = () => {
  return (
    <>
      <Head>
        <title>{`${appName} - ${"Categories"}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout title="Categories" navItems={unitNavItems}>
        Categories
      </Layout>
      ;
    </>
  );
};

export default Categories;
