import React from "react";
import Head from "next/head";
import Image from "next/image";
import { appName } from "@/utils";
import { t } from "@/locales";

const Offline = () => {
  return (
    <>
      <Head>
        <title>{`${appName} - ${t.offline.title}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="flex h-screen w-screen flex-col items-center justify-around p-8">
        <Image
          loader={({ src }) => src}
          src="/images/selam-jongeren-logo.svg"
          alt="Selam Jongeren logo"
          width={250}
          height={250}
        />
        <div className="flex flex-col items-center gap-4">
          <p>{t.offline.offlineText}</p>
        </div>
      </div>
    </>
  );
};

export default Offline;
