import { t } from "@/locales";
import { appName, Routes } from "@/utils";
import { Role } from "@prisma/client";
import { type NextPage } from "next";
import { unstable_getServerSession } from "next-auth";
import Head from "next/head";
import { authOptions } from "./api/auth/[...nextauth]";

const Home: NextPage = () => {
  return (
    <Head>
      <title>{`${appName} - ${t.common.homePage}`}</title>
      <meta name="description" content="Generated by create-t3-app" />
    </Head>
  );
};

export async function getServerSideProps({ req, res }) {
  const session = await unstable_getServerSession(req, res, authOptions);
  let destination = Routes.SIGN_IN;

  if (session && session.user) {
    const user = session.user;
    switch (user.role) {
      case Role.USER:
        destination = Routes.WAITING_ROOM;
        break;

      case Role.APP_ADMIN:
        destination = Routes.MOSQUES;
        break;

      case Role.MOSQUE_ADMIN:
        destination = Routes.ORGANISATIONS;
        break;

      case Role.ORGANISATION_ADMIN:
        destination = Routes.UNITS;
        break;

      case Role.UNIT_ADMIN:
        destination = Routes.EVENTS;
        break;

      default:
        break;
    }
  }

  return {
    redirect: {
      permanent: false,
      destination,
    },
  };
}

export default Home;
