import { EmptyState, Layout, LoadingIndicator } from "@/components";
import { Calendar, MonthSwitcher } from "@/events";
import { t } from "@/locales";
import { appName, api } from "@/utils";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import {
  endOfMonth,
  isSameDay,
  isToday,
  startOfMonth,
  startOfToday,
} from "date-fns";

const Home: NextPage = () => {
  const today = startOfToday();
  const [selectedDay, setSelectedDay] = useState<Date>(today);
  const [selectedMonth, setSelectedMonth] = useState(startOfMonth(today));

  const { data, isFetching } = api.event.getAllBetween.useQuery({
    startDate: startOfMonth(selectedMonth),
    endDate: endOfMonth(selectedMonth),
  });

  const eventsOfSelectedDay = data?.filter((event) =>
    isSameDay(selectedDay, event.date)
  );

  const handleChange = (day: Date) => {
    console.log(day);
    setSelectedDay(day);
  };

  const hasEventOnDate = (date: Date) => {
    const event = data?.find((event) => isSameDay(date, event.date));
    return event ? true : false;
  };

  return (
    <Layout title={t.signIn.title}>
      <Head>
        <title>{`${appName} - ${t.common.homePage}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex flex-grow flex-col gap-8 p-4">
        <MonthSwitcher
          month={selectedMonth}
          onChange={(date) => setSelectedMonth(date)}
        />
        <Calendar month={selectedMonth}>
          {(day) => (
            <div
              onClick={() => handleChange(day)}
              className={`text-gray-400 ${
                isToday(day) ? " bg-secondary bg-opacity-50" : ""
              }${isSameDay(day, selectedDay) ? " border border-black" : ""}${
                hasEventOnDate(day) ? " text-black" : ""
              } flex h-8 w-8 items-center justify-center rounded-full text-center`}
            >
              {day.getDate()}
            </div>
          )}
        </Calendar>
        {isFetching ? (
          <LoadingIndicator className="flex-grow" />
        ) : eventsOfSelectedDay?.length > 0 ? (
          eventsOfSelectedDay?.map((event) => (
            <div key={event.id}>
              <span>{event.name}</span>
              <span>{event.date.toString()}</span>
            </div>
          ))
        ) : (
          <EmptyState className="flex-grow" text={t.signIn.emptyText} />
        )}
      </main>
    </Layout>
  );
};

export default Home;
