import { Layout } from "@/components";
import { Calendar } from "@/events";
import { t } from "@/locales";
import { appName } from "@/utils";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { startOfMonth, startOfToday } from "date-fns";

const Home: NextPage = () => {
  const today = startOfToday();
  const [selectedDay, setSelectedDay] = useState<Date>(today);
  const [selectedMonth, setSelectedMonth] = useState(startOfMonth(today));

  const handleChange = (day: Date) => {
    console.log(day);
    setSelectedDay(day);
  };

  return (
    <Layout>
      <Head>
        <title>{`${appName} - ${t.common.homePage}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <h1>Home</h1>
        <Calendar
          selectedDay={selectedDay}
          month={selectedMonth}
          onChange={handleChange}
        />
      </main>
    </Layout>
  );
};

export default Home;
