import { Button } from "@/components/Button";
import { t } from "@/locales";
import { appName } from "@/utils";
import { signIn } from "next-auth/react";
import Head from "next/head";
import React from "react";

const SignIn = () => {
  const options = { callbackUrl: "http://localhost:3000/" };
  return (
    <>
      <Head>
        <title>{`${appName} - ${t.common.signIn}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center">
        <h1>Sign In</h1>
        <Button onClick={() => signIn("google", options)}>
          Sign in with google
        </Button>
      </div>
    </>
  );
};

export default SignIn;
