import { Button } from "@/components/Button";
import { t } from "@/locales";
import { appName } from "@/utils";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { FcGoogle } from "react-icons/fc";

const SignIn = () => {
  const options = { callbackUrl: "http://localhost:3000/" };
  const headerText = t.signIn.welcome.split("Selam Jongeren");
  return (
    <>
      <Head>
        <title>{`${appName} - ${t.common.signIn}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen flex-col items-center justify-around p-8">
        <Image
          loader={({ src }) => src}
          src="/images/selam-jongeren-logo.svg"
          alt="Selam Jongeren logo"
          width={250}
          height={250}
        />
        <div className="flex flex-col items-center gap-4">
          <h1 className="text-header2">
            {headerText.map((element) =>
              element === "" ? (
                <span key={element} className="text-primary">
                  Selam Jongeren
                </span>
              ) : (
                element
              )
            )}
          </h1>
          <p>{t.signIn.signInToContinue}</p>
        </div>
        <Button
          className="flex w-full items-center justify-center gap-2"
          onClick={() => signIn("google", options)}
        >
          {t.signIn.signInWithGoogle} <FcGoogle size={20} />
        </Button>
        <div>
          <p className="text-center italic">&quot;{t.signIn.hadith}&quot;</p>
          <p className="flex justify-end text-gray-400">
            {t.signIn.hadithSource}
          </p>
        </div>
      </div>
    </>
  );
};

export default SignIn;
