import { Layout } from "@/components";
import { appName } from "@/utils";
import Head from "next/head";
import React from "react";

const Organisations = () => {
  return (
    <>
      <Head>
        <title>{`${appName} - ${"Organisations"}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout title="Organisations">Organisations</Layout>
    </>
  );
};

export default Organisations;
